import { useEffect, useState } from "react";
import client from "../../api/client";
import StatusBadge from "../../components/StatusBadge";

const NEXT_STATUS = { PENDING: [{ label: "Accept booking", value: "ACCEPTED", className: "btn-primary" }, { label: "Reject", value: "REJECTED", className: "btn-danger" }], ACCEPTED: [{ label: "Start work", value: "IN_PROGRESS", className: "btn-primary" }], IN_PROGRESS: [{ label: "Mark completed", value: "COMPLETED", className: "btn-primary" }] };

export default function ProviderBookings() {
  const [bookings, setBookings] = useState([]); const [filter, setFilter] = useState("ALL"); const [error, setError] = useState(""); const [loading, setLoading] = useState(true);
  const load = async () => { try { const res = await client.get("/api/provider/bookings"); setBookings(res.data || []); setError(""); } catch (err) { setError(err.response?.data?.message || "Could not load provider bookings."); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const updateStatus = async (id, status) => { setError(""); try { await client.put(`/api/provider/bookings/${id}/status`, { status }); await load(); } catch (err) { setError(err.response?.data?.message || "Could not update booking."); } };
  const visible = filter === "ALL" ? bookings : bookings.filter((b) => b.status === filter);
  const mapUrl = (b) => b.latitude != null && b.longitude != null ? `https://www.google.com/maps?q=${b.latitude},${b.longitude}` : `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(b.address || "")}`;
  if (loading) return <div className="empty-state"><strong>Loading bookings…</strong><p>Fetching your customer requests.</p></div>;
  return <div><div className="page-title-row"><div><span className="eyebrow">CUSTOMER REQUESTS</span><h2>Bookings</h2><p>Accept a job, navigate to the customer and update the visit status.</p></div><button className="btn btn-ghost btn-sm" onClick={load}>Refresh</button></div>{error && <div className="alert alert-error">{error}</div>}<div className="filter-row">{["ALL","PENDING","ACCEPTED","IN_PROGRESS","COMPLETED","REJECTED","CANCELLED"].map((s) => <button key={s} className={`chip ${filter === s ? "chip-active" : ""}`} onClick={() => setFilter(s)}>{s.replace("_", " ")}</button>)}</div>{visible.length === 0 && <div className="empty-state"><strong>No bookings here</strong><p>New customer requests will appear here.</p></div>}<div className="booking-list">{visible.map((b) => <article key={b.id} className="booking-item premium-booking"><div className="booking-item-header"><div><span className="eyebrow">BOOKING #{b.id}</span><h3>{b.categoryName}</h3><p className="muted">{b.customerName} · {b.customerPhone}</p></div><StatusBadge status={b.status} /></div><div className="customer-visit"><div><span>Customer address</span><strong>{b.address}</strong></div><a className="btn btn-primary btn-sm" target="_blank" rel="noreferrer" href={mapUrl(b)}>⌖ Open map</a></div><div className="booking-meta"><span>📞 {b.customerPhone}</span><span>🕒 {b.scheduledDate ? new Date(b.scheduledDate).toLocaleString() : "Schedule not provided"}</span></div>{b.description && <p className="booking-description">{b.description}</p>}<div className="booking-item-actions">{(NEXT_STATUS[b.status] || []).map((action) => <button key={action.value} className={`btn btn-sm ${action.className}`} onClick={() => updateStatus(b.id, action.value)}>{action.label}</button>)}</div></article>)}</div></div>;
}
